export const CREATE_RACES = 'CREATE_RACES';
export const SET_CANDIDATE_WINNER = 'SET_CANDIDATE_WINNER';
export const SET_CANDIDATE_LOSER = 'SET_CANDIDATE_LOSER';
export const SET_ALL_CANDIDATES_TO_LOSER = 'SET_ALL_CANDIDATES_TO_LOSER';
export const SET_RACE_OVERRIDE = 'SET_RACE_OVERRIDE';
export const REMOVE_RACE_OVERRIDE = 'REMOVE_RACE_OVERRIDE';
export const SET_RACE_AP_CALLED = 'SET_RACE_AP_CALLED';
export const REMOVE_RACE_AP_CALLED = 'REMOVE_RACE_AP_CALLED';