# Generated by Django 2.1.1 on 2018-09-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0006_race_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='APElectionMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_election_id', models.CharField(max_length=10)),
                ('called', models.BooleanField(default=False)),
                ('tabulated', models.BooleanField(default=False)),
                ('override_ap_call', models.BooleanField(default=False)),
                ('override_ap_votes', models.BooleanField(default=False)),
                ('precincts_reporting', models.PositiveIntegerField(blank=True, null=True)),
                ('precincts_total', models.PositiveIntegerField(blank=True, null=True)),
                ('precincts_reporting_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('ballot_measure', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='election.BallotMeasure')),
                ('election', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='election.Election')),
            ],
            options={
                'verbose_name_plural': 'AP election meta data',
            },
        ),
    ]
