# Generated by Django 2.1.2 on 2018-10-26 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0003_office_senate_class'),
        ('election', '0006_race_description'),
        ('aploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.DateTimeField(auto_now=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='government.Body')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamber_calls', to='election.ElectionCycle')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamber_calls', to='government.Party')),
            ],
        ),
    ]
